// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// RcppLasso
List RcppLasso(NumericMatrix Xr, NumericVector yr, NumericMatrix Br, NumericVector lambdar, double stepsize, double maxIters);
RcppExport SEXP RGPULasso_RcppLasso(SEXP XrSEXP, SEXP yrSEXP, SEXP BrSEXP, SEXP lambdarSEXP, SEXP stepsizeSEXP, SEXP maxItersSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    NumericMatrix Xr = Rcpp::as<NumericMatrix >(XrSEXP);
    NumericVector yr = Rcpp::as<NumericVector >(yrSEXP);
    NumericMatrix Br = Rcpp::as<NumericMatrix >(BrSEXP);
    NumericVector lambdar = Rcpp::as<NumericVector >(lambdarSEXP);
    double stepsize = Rcpp::as<double >(stepsizeSEXP);
    double maxIters = Rcpp::as<double >(maxItersSEXP);
    List __result = RcppLasso(Xr, yr, Br, lambdar, stepsize, maxIters);
    return Rcpp::wrap(__result);
END_RCPP
}
